### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ellentkoch** [UBC-MDS/DSCI_532_group-106_supermarket#22]
Your dashboard has many interactive elements! If you find that it becomes a bit much to create in the time frame, feel free to set up a meeting with me to ensure the project can still be successful. @moniquewong @reikookamoto @clsu22

**Comment by reikookamoto** [comment]
@ellentkoch would we be dumbing down our visualization too much if we removed the tab feature (to toggle between the different stores) and visualized the data for all stores together? Just want to make sure our final product meets Firas'/TAs' expectations.

**Comment by ellentkoch** [comment]
@reikookamoto You could do that, or just include 2 or the 3 stores, if you think it gives you more time to spend on your visualizations. I think the dashboard will still be complex enough with all of the other elements you have. The same TAs mark Lab 1 and Lab 2 so I will be marking your dashboard.

**Comment by reikookamoto** [comment]
@ellentkoch We've split the work and managed to get one working `.py` file with the heat maps filtered by stores and another file with the barplots filtered by day of the week and time of day. I think all we have to do is "merge" the two files into a fully functioning dashboard. We'd love some help with combining the two files during the office hours today!

**Comment by ellentkoch** [comment]
@reikookamoto I can take a look today and try to help :)
