### ISSUE TITLE
Working directory for VS Code

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#28]
Do we have to set a working directory in our code for our .py file? My VS Code won't run the .csv file when it's specified as '../data/supermarket_sales_clean.csv' but it would when it's specified as 'data/supermarket_sales_clean.csv'. 

For some reason, on Reiko's computer it seems that the root of the app.py file is in src whereas for my computer it's recognizing the project root is the root. 

Do we have to set it in the code so that the code doesn't have to change for whose computer it's working on? 

@clsu22: what happens when you run it?

**Comment by reikookamoto** [comment]
My dashboard crashes when I remove the `..`
I'll ask the TA today about how to deal with this.

**Comment by clsu22** [comment]
Yes, I think working directory matters. When you are in `src` directory, '../data/supermarket_sales_clean.csv' works; and when you are in home directory, 'data/supermarket_sales_clean.csv' works. because different relative path.

**Comment by moniquewong** [comment]
This has been fixed to work with Heroku defaults.
