### ISSUE TITLE
#2: Recreate python plots in R in a jupyter notebook

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#49]
Recreate heat maps and bar plots in R

**Comment by moniquewong** [comment]
@moniquewong to recreate heat maps - will finish by Thursday 10am
@clsu22 to recreate bar plots - begin after Thursday 10am using Jupyter notebook created for heat maps

**Comment by moniquewong** [comment]
Heat maps recreated
See [pull request](https://github.com/UBC-MDS/DSCI_532_group-106_R_supermarket/pull/2) in R repo

**Comment by reikookamoto** [comment]
New heat maps and bar plots are found [here](https://github.com/UBC-MDS/DSCI_532_group-106_R_supermarket/blob/master/src/analysis.ipynb) in the R repo
