### ISSUE TITLE
#1: Add more instructions for user when using the app

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#50]
Maybe using dcc.Markdown 

Add instructions for how the heat maps work and how to compare between different days / times (when this is implemented)

**Comment by moniquewong** [comment]
Implemented first draft: See [pull request](https://github.com/UBC-MDS/DSCI_532_group-106_supermarket/pull/55)

**Comment by reikookamoto** [comment]
Guiding questions and examples alongside general descriptions complete. See [pull request(https://github.com/UBC-MDS/DSCI_532_group-106_supermarket/pull/65)
