### ISSUE TITLE
#3: Update README, proposal and app sketch for R app

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#53]
Instructions in milestone3:

You will be recreating your app using DashR. Now that your app is approaching its final state, you should update your README, proposal, and app sketch to match what your app will actually be doing and showing. As a rough guideline of effort, you should spend no more than 1-2 hours in total for this section. To help your TAs grading your work, instead of submitting a link to your file directly, you should submit a link that compares two commits of your proposal. We will show you how to do this in the lab session, but here is a guide to do this.

**Comment by reikookamoto** [comment]
Done. [R repo](https://github.com/UBC-MDS/DSCI_532_group-106_R_supermarket) is now up with appropriate files.
