### ISSUE TITLE
#5: Clean up folder structure and file names

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_532_group-106_supermarket#56]
- Change file names so that there are no duplicates and file names tell you what it is
- Specifically, rename files in `src` file

**Comment by reikookamoto** [comment]
1. analysis_draft.ipynb --> heatmap-charts.ipynb
2. app.py --> 04-milestone2.py
3. app_storefilter.py --> 02-heatmap.py
4. barplot_app.py --> 03-barplot.py
5. barplot_draft.ipynb --> barplot-charts.ipynb
6. old.py --> 01-heatmap.py
7. plot_1.html --> test-heatmap.html

**Comment by reikookamoto** [comment]
Done
